# Generated by Django 3.2.4 on 2021-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
